version: '3'
services:
  database:
    image: postgres:12.2-alpine
    container_name: mediumuh-db
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=mediumuh-db
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432