name: CD

on:
  push:
    branches:
      - 'master'

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Git identity
        env:
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
        run: |
          git config user.email "$GIT_USER_EMAIL"
          git config user.name "$GIT_USER_NAME"
      - name: Retrieve application's version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f pom.xml )
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create tag
        run: git tag -a "v$APP_VERSION-rc" -m "Release candidate v$APP_VERSION"
      - name: Push tag to repository
        run: git push --tags origin
